#Steps Specific Configuration
general:
Steps:
  gctsDeploy:
    host: 'http://172.16.10.101:8000'
    client: '100'
    abapCredentialsId: 'ABAPUserPasswordCredentialsId'
    repository: 'skondekar-shubh'
    remoteRepositoryURL: "https://github.com/skondekar/shubh"
    role: 'TARGET'
    vSID: 'S4D'
    branch: 'master'
    commit: 'commit'
    scope: 'scope'
    rollback: false
    configuration:
        dummyconfig: "dummyval"
  gctsExecuteABAPUnitTests:
      host: 'http://172.16.10.101:8000'
      client: '100'
      abapCredentialsId: 'ABAPUserPasswordCredentialsId'
      repository: 'skondekar-shubh'
      verbose: true
   gctsRollback:
      host: 'http://172.16.10.101:8000'
      client: '100'
      abapCredentialsId: 'ABAPUserPasswordCredentialsId'
      repository: 'skondekar-shubh'
