general:
Steps:
  gctsDeploy:
    host: 'http://10.34.156.145:8002'
    client: '300'
    abapCredentialsId: 'ABAPUserPasswordCredentialsId'
    repository: 'DEV003'
    remoteRepositoryURL: "https://github.com/skondekar/shubh"
    role: 'SOURCE'
    vSID: 'S4D'
    branch: 'master'
    commit: 'commit'
    scope: 'scope'
    rollback: false
    configuration:
        dummyconfig: "dummyval"
